version: "3.8"  # Versão da sintaxe do Compose

services:
  app:
    image: luizdurand/api-fastapi-nuvem:latest
    container_name: api_fastapi
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_DB: projeto
      POSTGRES_USER: projeto
      POSTGRES_PASSWORD: projeto
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: projeto
      POSTGRES_USER: projeto
      POSTGRES_PASSWORD: projeto
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: