services:
  app:
    image: luizdurand/api-fastapi-nuvem:latest
    container_name: api_fastapi
    ports:
      - "8080:8080"
    environment:
      # String de conexão SQLAlchemy para o MySQL
      DATABASE_URL: mysql+pymysql://cloud:cloud-n123@db:3306/p_cloud
      SECRET_KEY: troque_isto_por_uma_chave_secreta
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_projeto
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # ou outra senha de root
      MYSQL_DATABASE: p_cloud
      MYSQL_USER: cloud
      MYSQL_PASSWORD: cloud-n123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
