FROM python:3.10-slim

WORKDIR /app

# Corrigido: nome do arquivo de dependências
COPY requiriments.txt .
RUN pip install --no-cache-dir -r requiriments.txt

COPY . .

EXPOSE 8080

CMD ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "8080"]
